// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/drizzle/**',
      '**/.turbo/**',
      // Regenerated by Next.js on every build and explicitly marked "should not
      // be edited" — its triple-slash reference is Next's own, not ours, so
      // linting it only ever produces an error nobody is allowed to fix.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Build-tool config files at app roots (babel.config.js, postcss.config.js)
    // are CommonJS and run in Node — without this they trip `no-undef` on
    // `module`, which is the file's whole contract.
    files: ['**/*.config.js', '**/*.config.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { module: 'writable', require: 'readonly', process: 'readonly', __dirname: 'readonly' },
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // rules/code-reviewer.md's non-negotiables: no silent `any`, no unchecked
      // non-null assertions, no unvalidated `as` — enforced here, not just in review.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'off', // used deliberately post-RBAC-check; reviewed by the code-reviewer agent instead
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['error'] }],
    },
  },
);
